**Artificial Neural Network**

In [6]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [7]:
tf.__version__

'2.13.0'

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [9]:
print(y)

[1 0 1 ... 1 1 0]


**Encoding Categorical Data**

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


**Splitting Dataset and scaling**

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Initializing the ANN**

In [17]:
ann = tf.keras.models.Sequential()

**Adding first Hidden layer**

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

**Adding second Hidden layer**

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

**Adding the Output Layer**

In [20]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

**Training ANN**

In [21]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 3s 3ms/step - loss: 0.4796 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4494 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4362 - accuracy: 0.8000
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4265 - accuracy: 0.8125
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4166 - accuracy: 0.8216
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4068 - accuracy: 0.8270
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3968 - accuracy: 0.8328
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3868 - accuracy: 0.8374
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3790 - accuracy: 0.8416
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3731 - accura

**Predicting the Test Set Results**

In [23]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


**Making the Confusion matrix**

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1541   54]
 [ 212  193]]


0.867